apple_library(
    name = 'Pilot',
    swift_version = '4.2',
    srcs = [
        'Source/Mutex.swift',
        'Source/Async.swift',
        'Source/Observable/ObservableType.swift',
        'Source/Token.swift',
        'Source/Downcast.swift',
        'Source/Logging/Logger.swift',
        'Source/Logging/FileLogger.swift',
        'Source/Logging/ConsoleLogger.swift',
        'Source/MVVM/View.swift',
        'Source/MVVM/CompoundAction.swift',
        'Source/MVVM/SectionedModelCollection.swift',
        'Source/MVVM/Model.swift',
        'Source/MVVM/FilteredModelCollection.swift',
        'Source/MVVM/StaticModelCollection.swift',
        'Source/MVVM/AsyncModelCollection.swift',
        'Source/MVVM/ModelCollection.swift',
        'Source/MVVM/NestedModelCollection.swift',
        'Source/MVVM/ViewModelBinding.swift',
        'Source/MVVM/ComposedModelCollection.swift',
        'Source/MVVM/ViewModel.swift',
        'Source/MVVM/ViewModelUserEvents.swift',
        'Source/MVVM/SimpleModelCollection.swift',
        'Source/MVVM/StaticModel.swift',
        'Source/MVVM/SecondaryActionInfo.swift',
        'Source/MVVM/Context.swift',
        'Source/MVVM/EmptyModelCollection.swift',
        'Source/MVVM/DiffEngine.swift',
        'Source/MVVM/MappedModelCollection.swift',
        'Source/MVVM/ViewLayout.swift',
        'Source/MVVM/StaticViewBindingProvider.swift',
        'Source/MVVM/SwitchableModelCollection.swift',
        'Source/MVVM/Action.swift',
        'Source/MVVM/ScoredModelCollection.swift',
        'Source/MVVM/SortedModelCollection.swift',
    ],
    frameworks = [
        '$SDKROOT/System/Library/Frameworks/Foundation.framework',
    ],
    modular = True,
    tests = [':PilotTests'],
    info_plist = "Source/iOS-Info.plist",
    info_plist_substitutions = {
        'PRODUCT_BUNDLE_IDENTIFIER': 'com.dropbox.Pilot',
        'CURRENT_PROJECT_VERSION': '1'
    },
    visibility = ['PUBLIC']
)

apple_test(
    name = 'PilotTests',
    swift_version = '4.2',
    info_plist = 'Tests/Info.plist',
    info_plist_substitutions = {
        'PRODUCT_BUNDLE_IDENTIFIER': 'com.dropbox.PilotTests'
    },
    srcs = glob(['Tests/**/*.swift']),
    deps = [':Pilot'],
    frameworks = [
        '$SDKROOT/System/Library/Frameworks/Foundation.framework',
        '$PLATFORM_DIR/Developer/Library/Frameworks/XCTest.framework',
    ],
)
