
pilotui_shared_srcs = [
    "Source/Layout/LayoutConstraints.swift",
    "Source/Extensions/Collection.swift",
    "Source/Extensions/AssociatedObjects.swift",
    "Source/Alerts/AlertAction.swift",
    "Source/PlatformAliases.swift",
    "Source/CollectionViews/CollectionViewModelDataSource.swift",
    "Source/CollectionViews/CollectionViewInternals.swift",
    "Source/CollectionViews/CollectionHostedView.swift",    
]

apple_library(
    name = 'PilotUI-iOS',
    module_name = 'PilotUI',
    swift_version = '4.2',
    srcs =  pilotui_shared_srcs + 
            [
                "Source/Alerts/ios/UIAlertController+AlertAction.swift",
                "Source/CollectionViews/ios/CollectionViewHostCell.swift",
                "Source/CollectionViews/ios/CollectionViewHostReusableView.swift",
                "Source/CollectionViews/ios/CollectionViewController.swift",
            ],
    deps = ['//Core:Pilot'],
    frameworks = [
        '$SDKROOT/System/Library/Frameworks/Foundation.framework',
        '$SDKROOT/System/Library/Frameworks/UIKit.framework'
    ],
    modular = True,
    info_plist = 'Source/Info-iOS.plist',
    info_plist_substitutions = {
        'PRODUCT_BUNDLE_IDENTIFIER': 'com.dropbox.PilotUI',
        'CURRENT_PROJECT_VERSION': '1'
    },
    visibility = ['PUBLIC']
)

apple_library(
    name = 'PilotUI-macOS',
    module_name = 'PilotUI',
    swift_version = '4.2',
    srcs = pilotui_shared_srcs + 
            [
                "Source/Common/mac/ModelCollectionViewController.swift",
                "Source/Common/mac/ModelCollectionStateViewTypes.swift",
                "Source/OutlineViews/mac/OutlineViewModelDataSource.swift",
                "Source/OutlineViews/mac/NestedModelCollectionTreeController.swift",
                "Source/OutlineViews/mac/OutlineViewController.swift",
                "Source/CollectionViews/mac/CollectionView.swift",
                "Source/CollectionViews/mac/CollectionViewHostItem.swift",
                "Source/CollectionViews/mac/CollectionViewHostReusableView.swift",
                "Source/CollectionViews/mac/CollectionViewController.swift",
                "Source/AppKitExtensions/NSMenu+Action.swift",
                "Source/AppKitExtensions/NSEvent+Keys.swift",
                "Source/AppKitExtensions/NSCollectionView+Selection.swift",
                "Source/AppKitExtensions/NestableScrollView.swift",
            ],
    deps = ['//Core:Pilot'],
    tests = [':PilotUITests-macOS'],
    modular = True,
    frameworks = [
        '$SDKROOT/System/Library/Frameworks/Foundation.framework',
        '$SDKROOT/System/Library/Frameworks/AppKit.framework',
        '$SDKROOT/System/Library/Frameworks/CoreServices.framework'
    ],
    info_plist = 'Source/Info-macOS.plist',
    info_plist_substitutions = {
        'PRODUCT_BUNDLE_IDENTIFIER': 'com.dropbox.PilotUI',
        'CURRENT_PROJECT_VERSION': '1'
    },
    visibility = ['PUBLIC']
)

apple_test(
    swift_version = '4.2',
    name = 'PilotUITests-macOS',
    info_plist = 'Tests/Info-macOS.plist',
    info_plist_substitutions = {
        'PRODUCT_BUNDLE_IDENTIFIER': 'com.dropbox.PilotUITests',
    },
    srcs = glob(["Source/OutlineViews/mac/NestedModelCollectionTreeControllerTests.swift",
                "Tests/**/mac/*.swift"]),
    deps = ['//Core:Pilot'],
    frameworks = [
        '$SDKROOT/System/Library/Frameworks/Foundation.framework',
        '$PLATFORM_DIR/Developer/Library/Frameworks/XCTest.framework',
    ],
)